#!/usr/bin/env bash
# add-client.sh — Provision a new per-client Moodle instance.
# Usage: ./scripts/add-client.sh <client-name> <domain>
# Example: ./scripts/add-client.sh acme-corp acme-corp.com
#
# Prerequisites:
#   - Shared infrastructure (traefik, mariadb, redis) must be running.
#   - DNS A record for <domain> must point to this server's IP.
#   - Run from the repository root on the Droplet.
set -euo pipefail

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------
if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <client-name> <domain>"
    echo "Example: $0 acme-corp acme-corp.com"
    exit 1
fi

CLIENT_NAME="$1"
CLIENT_DOMAIN="$2"

# Validate client name: lowercase alphanumeric and hyphens only
if [[ ! "${CLIENT_NAME}" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$ ]]; then
    echo "ERROR: client-name must be lowercase alphanumeric with hyphens (e.g. acme-corp)"
    exit 1
fi

# Validate domain format (basic check)
if [[ ! "${CLIENT_DOMAIN}" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
    echo "ERROR: domain appears invalid: ${CLIENT_DOMAIN}"
    exit 1
fi

# Underscored variant for volume names and DB names (hyphens → underscores)
CLIENT_NAME_UNDER="${CLIENT_NAME//-/_}"
COMPOSE_DIR="clients/${CLIENT_NAME}"
COMPOSE_FILE="${COMPOSE_DIR}/docker-compose.yml"
ENV_FILE="${COMPOSE_DIR}/.env"

echo "==> Provisioning client: ${CLIENT_NAME} (${CLIENT_DOMAIN})"

# ---------------------------------------------------------------------------
# Guard: skip if already provisioned
# ---------------------------------------------------------------------------
if [[ -d "${COMPOSE_DIR}" ]]; then
    echo "WARNING: ${COMPOSE_DIR}/ already exists. Skipping provisioning."
    echo "To reprovision, remove ${COMPOSE_DIR}/ manually first."
    exit 0
fi

# ---------------------------------------------------------------------------
# Load shared infrastructure .env for DB credentials
# ---------------------------------------------------------------------------
if [[ ! -f ".env" ]]; then
    echo "ERROR: .env not found in repository root. Create it from .env.example first."
    exit 1
fi
# shellcheck disable=SC1091
source .env

required_infra_vars=(MARIADB_ROOT_PASSWORD MARIADB_PASSWORD ACME_EMAIL)
for var in "${required_infra_vars[@]}"; do
    if [[ -z "${!var:-}" ]]; then
        echo "ERROR: ${var} is not set in .env"
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Generate per-client credentials
# ---------------------------------------------------------------------------
MOODLE_PASSWORD="$(openssl rand -hex 16)"
DB_NAME="moodle_${CLIENT_NAME_UNDER}"

mkdir -p "${COMPOSE_DIR}"

cat > "${ENV_FILE}" <<ENVEOF
# Auto-generated by add-client.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT THIS FILE

CLIENT_NAME=${CLIENT_NAME}
CLIENT_DOMAIN=${CLIENT_DOMAIN}

MOODLE_USERNAME=admin
MOODLE_PASSWORD=${MOODLE_PASSWORD}
MOODLE_EMAIL=admin@${CLIENT_DOMAIN}
MOODLE_SITE_NAME=${CLIENT_NAME^} Learning
MOODLE_HOST=${CLIENT_DOMAIN}

MOODLE_DATABASE_HOST=mariadb
MOODLE_DATABASE_PORT_NUMBER=3306
MOODLE_DATABASE_USER=moodle
MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
MOODLE_DATABASE_NAME=${DB_NAME}

MOODLE_EXTRA_CONFIGPHP=<?php \$CFG->session_handler_class = '\core\session\redis'; \$CFG->session_redis_host = 'redis'; \$CFG->session_redis_port = 6379; \$CFG->session_redis_prefix = 'moodle_${CLIENT_NAME_UNDER}_session_'; \$CFG->session_redis_acquire_lock_timeout = 120; \$CFG->session_redis_lock_expire = 7200;
ENVEOF
chmod 600 "${ENV_FILE}"
echo "==> Created ${ENV_FILE}"

# ---------------------------------------------------------------------------
# Generate client docker-compose.yml from template
# ---------------------------------------------------------------------------
export CLIENT_NAME CLIENT_DOMAIN CLIENT_NAME_UNDER
envsubst "${CLIENT_NAME} ${CLIENT_DOMAIN} ${CLIENT_NAME_UNDER}" \
    < clients/_template/docker-compose.yml.tpl \
    > "${COMPOSE_FILE}"
echo "==> Created ${COMPOSE_FILE}"

# ---------------------------------------------------------------------------
# Create per-client MariaDB database
# ---------------------------------------------------------------------------
echo "==> Creating database: ${DB_NAME}"
docker compose exec mariadb \
    mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" \
    -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
        GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO 'moodle'@'%';
        FLUSH PRIVILEGES;"
echo "==> Database ${DB_NAME} ready."

# ---------------------------------------------------------------------------
# Add include: entry to root docker-compose.yml (idempotent)
# ---------------------------------------------------------------------------
INCLUDE_LINE="  - ${COMPOSE_FILE}"
if grep -qF "${INCLUDE_LINE}" docker-compose.yml; then
    echo "==> include entry already present in docker-compose.yml"
else
    # Insert after the include: key (or add the include: block before volumes:)
    if grep -q "^include:" docker-compose.yml; then
        # Append to existing include block
        sed -i "/^include:/a\\${INCLUDE_LINE}" docker-compose.yml
    else
        # Add include block before the volumes: section
        sed -i "/^volumes:/i\\include:\n${INCLUDE_LINE}\n" docker-compose.yml
    fi
    echo "==> Added include entry to docker-compose.yml"
fi

# ---------------------------------------------------------------------------
# Start the new Moodle container
# ---------------------------------------------------------------------------
echo "==> Starting moodle-${CLIENT_NAME} container..."
docker compose up -d "moodle-${CLIENT_NAME}"

echo "==> Waiting for moodle-${CLIENT_NAME} to become healthy (~5-8 min first run)..."
TIMEOUT=600
ELAPSED=0
until docker inspect --format='{{.State.Health.Status}}' \
    "$(docker compose ps -q moodle-"${CLIENT_NAME}")" 2>/dev/null | grep -q "healthy"; do
    if [[ ${ELAPSED} -ge ${TIMEOUT} ]]; then
        echo "ERROR: moodle-${CLIENT_NAME} did not become healthy within ${TIMEOUT}s"
        docker compose logs "moodle-${CLIENT_NAME}" | tail -30
        exit 1
    fi
    sleep 15
    ELAPSED=$((ELAPSED + 15))
    echo "  ...still waiting (${ELAPSED}s elapsed)"
done
echo "==> moodle-${CLIENT_NAME} is healthy."

# ---------------------------------------------------------------------------
# Run the seed container
# ---------------------------------------------------------------------------
echo "==> Running seed for ${CLIENT_NAME}..."
docker compose run --rm "seed-${CLIENT_NAME}"
echo "==> Seed complete."

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "=========================================="
echo "  Client provisioned successfully!"
echo "=========================================="
echo "  Name   : ${CLIENT_NAME}"
echo "  URL    : https://${CLIENT_DOMAIN}"
echo "  Admin  : admin / ${MOODLE_PASSWORD}"
echo "  DB     : ${DB_NAME}"
echo "  Env    : ${ENV_FILE}"
echo "=========================================="
echo "  Store credentials securely — this is the only time the password is shown."
echo ""
